"""add_actor_xyz_to_fire_weapon_events

Revision ID: 088f97b42929
Revises: 0b20b0747e3d
Create Date: 2026-06-11 09:06:50.885354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088f97b42929'
down_revision: Union[str, Sequence[str], None] = '0b20b0747e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fire_weapon_events', sa.Column('actor_x', sa.Float(), nullable=True))
    op.add_column('fire_weapon_events', sa.Column('actor_y', sa.Float(), nullable=True))
    op.add_column('fire_weapon_events', sa.Column('actor_z', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fire_weapon_events', 'actor_z')
    op.drop_column('fire_weapon_events', 'actor_y')
    op.drop_column('fire_weapon_events', 'actor_x')
    # ### end Alembic commands ###
