"""add_fire_weapon_events_table

Revision ID: 0b20b0747e3d
Revises: 8a4f2c1d9b7e
Create Date: 2026-06-10 19:31:18.195705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b20b0747e3d'
down_revision: Union[str, Sequence[str], None] = '8a4f2c1d9b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fire_weapon_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_time_seconds', sa.Float(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.String(length=200), nullable=False),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Float(), nullable=False),
    sa.Column('actual_damage', sa.Float(), nullable=False),
    sa.Column('harvest', sa.Boolean(), nullable=False),
    sa.Column('hit_player', sa.Boolean(), nullable=False),
    sa.Column('hit_critical', sa.Boolean(), nullable=False),
    sa.Column('hit_player_build', sa.Boolean(), nullable=False),
    sa.Column('hit_fatal', sa.Boolean(), nullable=False),
    sa.Column('hit_shield', sa.Boolean(), nullable=False),
    sa.Column('hit_ballistic', sa.Boolean(), nullable=False),
    sa.Column('destroyed_shield', sa.Boolean(), nullable=False),
    sa.Column('hit_player_id', sa.Integer(), nullable=True),
    sa.Column('hit_result', sa.String(length=50), nullable=True),
    sa.Column('hit_actor_id', sa.Integer(), nullable=True),
    sa.Column('end_x', sa.Float(), nullable=True),
    sa.Column('end_y', sa.Float(), nullable=True),
    sa.Column('end_z', sa.Float(), nullable=True),
    sa.Column('item_entry_guid', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hit_player_id'], ['match_players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fwe_actor', 'fire_weapon_events', ['actor_id'], unique=False)
    op.create_index('idx_fwe_hit_player', 'fire_weapon_events', ['hit_player_id'], unique=False)
    op.create_index('idx_fwe_match', 'fire_weapon_events', ['match_id'], unique=False)
    op.create_index('idx_fwe_time', 'fire_weapon_events', ['game_time_seconds'], unique=False)
    op.create_index('idx_fwe_weapon', 'fire_weapon_events', ['weapon_id'], unique=False)
    op.create_index('idx_fwe_zone', 'fire_weapon_events', ['zone'], unique=False)
    op.alter_column('damage_dealt_events', 'game_time_seconds',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('elimination_events', 'game_time_seconds',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('elimination_events', 'game_time_seconds',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('damage_dealt_events', 'game_time_seconds',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index('idx_fwe_zone', table_name='fire_weapon_events')
    op.drop_index('idx_fwe_weapon', table_name='fire_weapon_events')
    op.drop_index('idx_fwe_time', table_name='fire_weapon_events')
    op.drop_index('idx_fwe_match', table_name='fire_weapon_events')
    op.drop_index('idx_fwe_hit_player', table_name='fire_weapon_events')
    op.drop_index('idx_fwe_actor', table_name='fire_weapon_events')
    op.drop_table('fire_weapon_events')
    # ### end Alembic commands ###
