"""add_assist_events_table

Revision ID: 1c031ba5534d
Revises: b59d8e1e7d65
Create Date: 2026-06-19 13:34:51.368456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c031ba5534d'
down_revision: Union[str, Sequence[str], None] = 'b59d8e1e7d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assist_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_time_seconds', sa.Float(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('victim_id', sa.Integer(), nullable=False),
    sa.Column('killer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['killer_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['victim_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assist_actor', 'assist_events', ['actor_id'], unique=False)
    op.create_index('idx_assist_killer', 'assist_events', ['killer_id'], unique=False)
    op.create_index('idx_assist_match', 'assist_events', ['match_id'], unique=False)
    op.create_index('idx_assist_time', 'assist_events', ['game_time_seconds'], unique=False)
    op.create_index('idx_assist_victim', 'assist_events', ['victim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assist_victim', table_name='assist_events')
    op.drop_index('idx_assist_time', table_name='assist_events')
    op.drop_index('idx_assist_match', table_name='assist_events')
    op.drop_index('idx_assist_killer', table_name='assist_events')
    op.drop_index('idx_assist_actor', table_name='assist_events')
    op.drop_table('assist_events')
    # ### end Alembic commands ###
