"""add build_placed_events table

Revision ID: 3b60b8768696
Revises: 93c7d59215af
Create Date: 2026-07-05 01:41:58.338832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b60b8768696'
down_revision: Union[str, Sequence[str], None] = '93c7d59215af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_placed_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_time_seconds', sa.Float(), nullable=True),
    sa.Column('builder_id', sa.Integer(), nullable=False),
    sa.Column('build_type', sa.String(length=200), nullable=True),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('location_z', sa.Float(), nullable=True),
    sa.Column('build_actor_id', sa.Integer(), nullable=True),
    sa.Column('edited_actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['builder_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buildplaced_builder', 'build_placed_events', ['builder_id'], unique=False)
    op.create_index('idx_buildplaced_match', 'build_placed_events', ['match_id'], unique=False)
    op.create_index('idx_buildplaced_time', 'build_placed_events', ['game_time_seconds'], unique=False)
    op.create_index('idx_buildplaced_type', 'build_placed_events', ['build_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buildplaced_type', table_name='build_placed_events')
    op.drop_index('idx_buildplaced_time', table_name='build_placed_events')
    op.drop_index('idx_buildplaced_match', table_name='build_placed_events')
    op.drop_index('idx_buildplaced_builder', table_name='build_placed_events')
    op.drop_table('build_placed_events')
    # ### end Alembic commands ###
