"""add_distance_to_fire_weapon_events

Revision ID: 4cbded1fd854
Revises: 088f97b42929
Create Date: 2026-06-11 09:24:31.135526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbded1fd854'
down_revision: Union[str, Sequence[str], None] = '088f97b42929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fire_weapon_events', sa.Column('distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fire_weapon_events', 'distance')
    # ### end Alembic commands ###
