"""add_reboot_events_table

Revision ID: 8f53e8594ea2
Revises: 6e56d087522e
Create Date: 2026-07-03 18:08:15.222516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f53e8594ea2'
down_revision: Union[str, Sequence[str], None] = '6e56d087522e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reboot_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_time_seconds', sa.Float(), nullable=True),
    sa.Column('rebooted_id', sa.Integer(), nullable=False),
    sa.Column('rebooter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rebooted_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rebooter_id'], ['match_players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reboot_match', 'reboot_events', ['match_id'], unique=False)
    op.create_index('idx_reboot_rebooted', 'reboot_events', ['rebooted_id'], unique=False)
    op.create_index('idx_reboot_rebooter', 'reboot_events', ['rebooter_id'], unique=False)
    op.create_index('idx_reboot_time', 'reboot_events', ['game_time_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reboot_time', table_name='reboot_events')
    op.drop_index('idx_reboot_rebooter', table_name='reboot_events')
    op.drop_index('idx_reboot_rebooted', table_name='reboot_events')
    op.drop_index('idx_reboot_match', table_name='reboot_events')
    op.drop_table('reboot_events')
    # ### end Alembic commands ###
