"""add revive_events table

Revision ID: 93c7d59215af
Revises: dbafa0b64f34
Create Date: 2026-07-05 00:44:32.806972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c7d59215af'
down_revision: Union[str, Sequence[str], None] = 'dbafa0b64f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revive_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_time_seconds', sa.Float(), nullable=True),
    sa.Column('revived_id', sa.Integer(), nullable=False),
    sa.Column('reviver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revived_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviver_id'], ['match_players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_revive_match', 'revive_events', ['match_id'], unique=False)
    op.create_index('idx_revive_revived', 'revive_events', ['revived_id'], unique=False)
    op.create_index('idx_revive_reviver', 'revive_events', ['reviver_id'], unique=False)
    op.create_index('idx_revive_time', 'revive_events', ['game_time_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_revive_time', table_name='revive_events')
    op.drop_index('idx_revive_reviver', table_name='revive_events')
    op.drop_index('idx_revive_revived', table_name='revive_events')
    op.drop_index('idx_revive_match', table_name='revive_events')
    op.drop_table('revive_events')
    # ### end Alembic commands ###
