"""add_shot_attempt_events_table

Revision ID: a4431bea9c5d
Revises: 1c031ba5534d
Create Date: 2026-06-24 17:55:01.025786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4431bea9c5d'
down_revision: Union[str, Sequence[str], None] = '1c031ba5534d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shot_attempt_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_time_seconds', sa.Float(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.String(length=200), nullable=True),
    sa.Column('direct_hit', sa.Boolean(), nullable=False),
    sa.Column('passing_distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shotatt_actor', 'shot_attempt_events', ['actor_id'], unique=False)
    op.create_index('idx_shotatt_match', 'shot_attempt_events', ['match_id'], unique=False)
    op.create_index('idx_shotatt_recipient', 'shot_attempt_events', ['recipient_id'], unique=False)
    op.create_index('idx_shotatt_time', 'shot_attempt_events', ['game_time_seconds'], unique=False)
    op.create_index('idx_shotatt_weapon', 'shot_attempt_events', ['weapon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shotatt_weapon', table_name='shot_attempt_events')
    op.drop_index('idx_shotatt_time', table_name='shot_attempt_events')
    op.drop_index('idx_shotatt_recipient', table_name='shot_attempt_events')
    op.drop_index('idx_shotatt_match', table_name='shot_attempt_events')
    op.drop_index('idx_shotatt_actor', table_name='shot_attempt_events')
    op.drop_table('shot_attempt_events')
    # ### end Alembic commands ###
