"""add knock events table

Revision ID: b0dcd51bc3d6
Revises: ff9b8d8dfa2c
Create Date: 2026-10-08 16:02:39.283261

Adds ``knock_events`` — one row per knock of an opponent, from the
``knockedDownEvents`` log (the ``knocks`` registry stat), shaped like
``elimination_events``. Self-knocks and knocks on a teammate are excluded.
Starts empty; the reconciler fills it (``process_tournaments --all`` for every
match already ingested).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dcd51bc3d6'
down_revision: Union[str, Sequence[str], None] = 'ff9b8d8dfa2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knock_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_time_seconds', sa.Float(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('gun_type', sa.Integer(), nullable=True),
    sa.Column('actor_x', sa.Float(), nullable=False),
    sa.Column('actor_y', sa.Float(), nullable=False),
    sa.Column('actor_z', sa.Float(), nullable=False),
    sa.Column('recipient_x', sa.Float(), nullable=False),
    sa.Column('recipient_y', sa.Float(), nullable=False),
    sa.Column('recipient_z', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('zone', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knock_actor', 'knock_events', ['actor_id'], unique=False)
    op.create_index('idx_knock_match', 'knock_events', ['match_id'], unique=False)
    op.create_index('idx_knock_recipient', 'knock_events', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_knock_recipient', table_name='knock_events')
    op.drop_index('idx_knock_match', table_name='knock_events')
    op.drop_index('idx_knock_actor', table_name='knock_events')
    op.drop_table('knock_events')
    # ### end Alembic commands ###
