"""add_damage_contribution_events_table

Revision ID: b59d8e1e7d65
Revises: 4cbded1fd854
Create Date: 2026-06-18 16:19:25.836019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59d8e1e7d65'
down_revision: Union[str, Sequence[str], None] = '4cbded1fd854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_contribution_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('game_time_seconds', sa.Float(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('victim_id', sa.Integer(), nullable=False),
    sa.Column('killer_id', sa.Integer(), nullable=False),
    sa.Column('damage_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['killer_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['victim_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dce_actor', 'damage_contribution_events', ['actor_id'], unique=False)
    op.create_index('idx_dce_killer', 'damage_contribution_events', ['killer_id'], unique=False)
    op.create_index('idx_dce_match', 'damage_contribution_events', ['match_id'], unique=False)
    op.create_index('idx_dce_time', 'damage_contribution_events', ['game_time_seconds'], unique=False)
    op.create_index('idx_dce_victim', 'damage_contribution_events', ['victim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dce_victim', table_name='damage_contribution_events')
    op.drop_index('idx_dce_time', table_name='damage_contribution_events')
    op.drop_index('idx_dce_match', table_name='damage_contribution_events')
    op.drop_index('idx_dce_killer', table_name='damage_contribution_events')
    op.drop_index('idx_dce_actor', table_name='damage_contribution_events')
    op.drop_table('damage_contribution_events')
    # ### end Alembic commands ###
