"""add alive_intervals table

Revision ID: dbafa0b64f34
Revises: 8f53e8594ea2
Create Date: 2026-07-04 03:14:06.298009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbafa0b64f34'
down_revision: Union[str, Sequence[str], None] = '8f53e8594ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alive_intervals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alive_end', 'alive_intervals', ['end_seconds'], unique=False)
    op.create_index('idx_alive_match', 'alive_intervals', ['match_id'], unique=False)
    op.create_index('idx_alive_player', 'alive_intervals', ['player_id'], unique=False)
    op.create_index('idx_alive_start', 'alive_intervals', ['start_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alive_start', table_name='alive_intervals')
    op.drop_index('idx_alive_player', table_name='alive_intervals')
    op.drop_index('idx_alive_match', table_name='alive_intervals')
    op.drop_index('idx_alive_end', table_name='alive_intervals')
    op.drop_table('alive_intervals')
    # ### end Alembic commands ###
