"""add cosmetics augments static items tables

Revision ID: ff9b8d8dfa2c
Revises: f3a9c1d47b52
Create Date: 2026-10-06 03:29:31.312184

Adds the image catalogs behind inventory and loadout display, plus per-match
player loadouts:

* ``cosmetics`` — fnapi ``/v1/cosmetics`` + ``/v1/cosmetics/banners``
  (``etl/jobs/sync_cosmetics.py``)
* ``augments`` — fnapi ``/v1/augments`` (``etl/jobs/sync_augments.py``)
* ``static_items`` — hand-maintained consumables/ammo/materials map
  (``etl/static/items.py``, ``etl/jobs/sync_static_items.py``)
* ``match_player_cosmetics`` — each player's equipped cosmetic per loadout slot,
  from the ``cosmeticsV2`` match log (the ``cosmetics`` registry stat).

All tables start empty: run the three sync jobs; the reconciler fills
``match_player_cosmetics`` (``process_tournaments --all`` for matches already
ingested).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9b8d8dfa2c'
down_revision: Union[str, Sequence[str], None] = 'f3a9c1d47b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('augments',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('gameplay_tags', sa.JSON(), nullable=True),
    sa.Column('image_key', sa.String(length=300), nullable=True),
    sa.Column('small_image_key', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('small_image_url', sa.String(length=500), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cosmetics',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('cosmetic_type', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('set_name', sa.String(length=200), nullable=True),
    sa.Column('series_name', sa.String(length=100), nullable=True),
    sa.Column('introduction_season', sa.Integer(), nullable=True),
    sa.Column('introduction', sa.String(length=100), nullable=True),
    sa.Column('gameplay_tags', sa.JSON(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('image_key', sa.String(length=300), nullable=True),
    sa.Column('small_image_key', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('small_image_url', sa.String(length=500), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cosmetic_rarity', 'cosmetics', ['rarity'], unique=False)
    op.create_index('idx_cosmetic_type', 'cosmetics', ['cosmetic_type'], unique=False)
    op.create_table('static_items',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('alias_of', sa.String(length=200), nullable=True),
    sa.Column('image_key', sa.String(length=300), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_static_item_category', 'static_items', ['category'], unique=False)
    op.create_table('match_player_cosmetics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('loadout_slot', sa.String(length=50), nullable=False),
    sa.Column('cosmetic_id', sa.String(length=100), nullable=False),
    sa.Column('styles', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mpc_cosmetic', 'match_player_cosmetics', ['cosmetic_id'], unique=False)
    op.create_index('idx_mpc_match', 'match_player_cosmetics', ['match_id'], unique=False)
    op.create_index('idx_mpc_player_slot', 'match_player_cosmetics', ['player_id', 'loadout_slot'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mpc_player_slot', table_name='match_player_cosmetics')
    op.drop_index('idx_mpc_match', table_name='match_player_cosmetics')
    op.drop_index('idx_mpc_cosmetic', table_name='match_player_cosmetics')
    op.drop_table('match_player_cosmetics')
    op.drop_index('idx_static_item_category', table_name='static_items')
    op.drop_table('static_items')
    op.drop_index('idx_cosmetic_type', table_name='cosmetics')
    op.drop_index('idx_cosmetic_rarity', table_name='cosmetics')
    op.drop_table('cosmetics')
    op.drop_table('augments')
    # ### end Alembic commands ###
